name: 'amazon_ads_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  amazon_ads__ad_group_passthrough_metrics: []
  amazon_ads__advertised_product_passthrough_metrics: []
  amazon_ads__campaign_passthrough_metrics: []
  amazon_ads__search_term_ad_keyword_passthrough_metrics: []
  amazon_ads__targeting_keyword_passthrough_metrics: []

models:
  amazon_ads_source:
    tmp:
      +materialized: view
    +materialized: table
    +schema: amazon_ads_source